use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TemplateRender {
    pub workflows_yaml: String,
    pub script: String,
}

#[derive(Debug, Clone, Copy)]
enum Language {
    TypeScript,
    Rust,
    Python,
    Go,
    Java,
    Ruby,
    Other,
}

impl Language {
    fn parse(s: &str) -> Self {
        match s.to_ascii_lowercase().as_str() {
            "typescript" | "ts" | "javascript" | "js" | "node" => Language::TypeScript,
            "rust" | "rs" => Language::Rust,
            "python" | "py" => Language::Python,
            "go" | "golang" => Language::Go,
            "java" | "jvm" => Language::Java,
            "ruby" | "rb" => Language::Ruby,
            _ => Language::Other,
        }
    }
}

#[tauri::command]
pub async fn template_render(
    language: String,
    template: String,
) -> Result<TemplateRender, String> {
    if template != "ci-cd" {
        return Err(format!(
            "template '{template}' is not supported; only 'ci-cd' is available in v1"
        ));
    }

    let lang = Language::parse(&language);
    let workflows_yaml = render_workflow(lang);
    Ok(TemplateRender {
        workflows_yaml,
        script: GH_STATUS_POST_SCRIPT.to_string(),
    })
}

pub fn render_workflow_for(language: &str, template: &str) -> Result<TemplateRender, String> {
    if template != "ci-cd" {
        return Err(format!(
            "template '{template}' is not supported; only 'ci-cd' is available in v1"
        ));
    }
    let lang = Language::parse(language);
    Ok(TemplateRender {
        workflows_yaml: render_workflow(lang),
        script: GH_STATUS_POST_SCRIPT.to_string(),
    })
}

fn render_workflow(lang: Language) -> String {
    let header = workflow_header(lang);
    let install = phase_block(
        "install",
        install_program(lang),
        install_args(lang),
        600,
    );
    let lint = phase_block("lint", lint_program(lang), lint_args(lang), 300);
    let test = phase_block("test", test_program(lang), test_args(lang), 900);
    let build = if has_build_phase(lang) {
        Some(phase_block(
            "build",
            build_program(lang),
            build_args(lang),
            600,
        ))
    } else {
        None
    };

    let status_success = r#"  status-success:
    mode: command
    command:
      program: ./scripts/gh-status-post.sh
      args: [success]
      timeout_secs: 60
"#;
    let status_failure = r#"  status-failure:
    mode: command
    command:
      program: ./scripts/gh-status-post.sh
      args: [failure]
      timeout_secs: 60
"#;

    let mut phases_section = String::from("phases:\n");
    phases_section.push_str(&install);
    phases_section.push('\n');
    phases_section.push_str(&lint);
    phases_section.push('\n');
    phases_section.push_str(&test);
    phases_section.push('\n');
    if let Some(b) = build.as_ref() {
        phases_section.push_str(b);
        phases_section.push('\n');
    }
    phases_section.push_str(status_success);
    phases_section.push('\n');
    phases_section.push_str(status_failure);

    let mut workflow_phases = String::new();
    workflow_phases.push_str("      - install\n");
    workflow_phases.push_str("      - lint\n");
    workflow_phases.push_str("      - test\n");
    if build.is_some() {
        workflow_phases.push_str("      - build\n");
    }
    workflow_phases.push_str("      - status-success\n");

    let workflows_section = format!(
        "workflows:\n  - id: pr-ci\n    phases:\n{workflow_phases}"
    );

    let triggers_section = r#"triggers:
  - id: pr-opened
    type: github_webhook
    workflow_ref: pr-ci
    enabled: true
    config:
      events: [pull_request]
      actions: [opened, reopened, synchronize]
"#;

    format!(
        "{header}\nagents: {{}}\n\n{phases_section}\n{workflows_section}\n{triggers_section}"
    )
}

fn phase_block(name: &str, program: &str, args: &[&str], timeout: u32) -> String {
    let args_str = if args.is_empty() {
        "[]".to_string()
    } else {
        format!("[{}]", args.join(", "))
    };
    format!(
        "  {name}:\n    mode: command\n    command:\n      program: {program}\n      args: {args_str}\n      timeout_secs: {timeout}\n      success_exit_codes: [0]\n"
    )
}

fn workflow_header(lang: Language) -> &'static str {
    match lang {
        Language::TypeScript => {
            "# CI/CD team template — TypeScript\n#\n# Generated by Animus Desktop. Drops in at .animus/workflows.yaml.\n# Requires Animus v0.5.3+, gh CLI authenticated, and the\n# github_webhook plugin installed.\n"
        }
        Language::Rust => {
            "# CI/CD team template — Rust\n#\n# Generated by Animus Desktop. Adjust command flags to taste.\n"
        }
        Language::Python => {
            "# CI/CD team template — Python\n#\n# Generated by Animus Desktop. Uses uv by default; swap to\n# `pip install -e .` if your project is pip-based.\n"
        }
        Language::Go => {
            "# CI/CD team template — Go\n#\n# Generated by Animus Desktop.\n"
        }
        Language::Java => {
            "# CI/CD team template — Java (Maven)\n#\n# Generated by Animus Desktop. If you use Gradle, swap\n# `mvn` for `./gradlew` and adapt args.\n"
        }
        Language::Ruby => {
            "# CI/CD team template — Ruby\n#\n# Generated by Animus Desktop.\n"
        }
        Language::Other => {
            "# CI/CD team template — generic\n#\n# Generated by Animus Desktop. The command shapes default\n# to the TypeScript reference — edit each phase to match\n# your stack before enabling.\n"
        }
    }
}

fn install_program(lang: Language) -> &'static str {
    match lang {
        Language::TypeScript | Language::Other => "npm",
        Language::Rust => "cargo",
        Language::Python => "uv",
        Language::Go => "go",
        Language::Java => "mvn",
        Language::Ruby => "bundle",
    }
}

fn install_args(lang: Language) -> &'static [&'static str] {
    match lang {
        Language::TypeScript | Language::Other => &["ci"],
        Language::Rust => &["fetch"],
        Language::Python => &["sync"],
        Language::Go => &["mod", "download"],
        Language::Java => &["dependency:resolve"],
        Language::Ruby => &["install"],
    }
}

fn lint_program(lang: Language) -> &'static str {
    match lang {
        Language::TypeScript | Language::Other => "npm",
        Language::Rust => "cargo",
        Language::Python => "ruff",
        Language::Go => "golangci-lint",
        Language::Java => "mvn",
        Language::Ruby => "bundle",
    }
}

fn lint_args(lang: Language) -> &'static [&'static str] {
    match lang {
        Language::TypeScript | Language::Other => &["run", "lint"],
        Language::Rust => &["clippy", "--all-targets", "--", "-D", "warnings"],
        Language::Python => &["check", "."],
        Language::Go => &["run"],
        Language::Java => &["verify", "-DskipTests"],
        Language::Ruby => &["exec", "rubocop"],
    }
}

fn test_program(lang: Language) -> &'static str {
    match lang {
        Language::TypeScript | Language::Other => "npm",
        Language::Rust => "cargo",
        Language::Python => "pytest",
        Language::Go => "go",
        Language::Java => "mvn",
        Language::Ruby => "bundle",
    }
}

fn test_args(lang: Language) -> &'static [&'static str] {
    match lang {
        Language::TypeScript | Language::Other => &["test"],
        Language::Rust => &["test"],
        Language::Python => &[],
        Language::Go => &["test", "./..."],
        Language::Java => &["test"],
        Language::Ruby => &["exec", "rspec"],
    }
}

fn has_build_phase(lang: Language) -> bool {
    !matches!(lang, Language::Python | Language::Ruby)
}

fn build_program(lang: Language) -> &'static str {
    match lang {
        Language::TypeScript | Language::Other => "npm",
        Language::Rust => "cargo",
        Language::Go => "go",
        Language::Java => "mvn",
        Language::Python | Language::Ruby => "true",
    }
}

fn build_args(lang: Language) -> &'static [&'static str] {
    match lang {
        Language::TypeScript | Language::Other => &["run", "build"],
        Language::Rust => &["build", "--release"],
        Language::Go => &["build", "./..."],
        Language::Java => &["package", "-DskipTests"],
        Language::Python | Language::Ruby => &[],
    }
}

pub const GH_STATUS_POST_SCRIPT: &str = r#"#!/usr/bin/env bash
# gh-status-post.sh — post a PR status check via the gh CLI.
#
# Usage:
#   gh-status-post.sh success
#   gh-status-post.sh failure
#   gh-status-post.sh pending
#
# Required environment (Animus injects these into command phases that
# run from a webhook-triggered workflow):
#   GITHUB_REPO        e.g. launchapp-dev/animus-cli
#   COMMIT_SHA         the head SHA of the PR
#
# Optional:
#   STATUS_CONTEXT     defaults to "animus/ci"
#   TARGET_URL         link the status check points at (e.g. dashboard)

set -euo pipefail

STATUS="${1:-success}"
REPO="${GITHUB_REPO:?GITHUB_REPO must be set}"
SHA="${COMMIT_SHA:?COMMIT_SHA must be set}"
CONTEXT="${STATUS_CONTEXT:-animus/ci}"
TARGET="${TARGET_URL:-}"

case "$STATUS" in
  success)
    DESCRIPTION="Animus CI passed locally"
    ;;
  failure)
    DESCRIPTION="Animus CI failed locally"
    ;;
  pending)
    DESCRIPTION="Animus CI running locally"
    ;;
  *)
    echo "gh-status-post.sh: unknown status '$STATUS' (expected success/failure/pending)" >&2
    exit 2
    ;;
esac

ARGS=(
  api
  "repos/${REPO}/statuses/${SHA}"
  -X POST
  -f "state=${STATUS}"
  -f "description=${DESCRIPTION}"
  -f "context=${CONTEXT}"
)

if [ -n "$TARGET" ]; then
  ARGS+=(-f "target_url=${TARGET}")
fi

gh "${ARGS[@]}"
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_all_languages() {
        for lang in [
            "typescript",
            "rust",
            "python",
            "go",
            "java",
            "ruby",
            "other",
        ] {
            let r = render_workflow_for(lang, "ci-cd").expect("render ok");
            assert!(r.workflows_yaml.contains("agents: {}"));
            assert!(r.workflows_yaml.contains("phases:"));
            assert!(r.workflows_yaml.contains("workflows:"));
            assert!(r.workflows_yaml.contains("triggers:"));
            assert!(r.workflows_yaml.contains("pr-ci"));
            assert!(r.workflows_yaml.contains("status-success"));
            assert!(r.workflows_yaml.contains("status-failure"));
            assert!(r.script.starts_with("#!/usr/bin/env bash"));
        }
    }

    #[test]
    fn python_and_ruby_drop_build_phase() {
        for lang in ["python", "ruby"] {
            let r = render_workflow_for(lang, "ci-cd").expect("render ok");
            assert!(
                !r.workflows_yaml.contains("  build:"),
                "{lang} should drop build phase"
            );
            assert!(!r.workflows_yaml.contains("      - build\n"));
        }
    }

    #[test]
    fn rejects_unknown_template() {
        let err = render_workflow_for("rust", "trading").unwrap_err();
        assert!(err.contains("trading"));
    }
}
